# Generated by Django 4.1.7 on 2023-03-17 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_like_date_created_like_unique_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
